### ISSUE TITLE
Detection of cancellations

### ISSUE THREAD

**Issue by ffevotte** [edf-hpc/verrou#13]
It would be useful to (re)introduce in Verrou a feature allowing to detect and locate large cancellations.

**Comment by lathuili** [comment]
The option  _--check-cancellation=yes_ now produces a valgrind error for each cancellation.
The option _--cc-gen-file=_FILENAME produces a file called FILENAME with the list of code lines generating cancellation.

You can configure the level of cancellation with the options _--cc_threshold_double=_ and _--cc_threshold_float=_ .
