### ISSUE TITLE
Consider capping verrou_dd's delta list length

### ISSUE THREAD

**Issue by HadrienG2** [edf-hpc/verrou#14]
A debug build of a C++ program can use _thousands_ of symbols. In this scenario, verrou_dd's helpful printout of the list of deltas can become a nuisance, as it heavily clobbers the TTY and makes it hard to locate previous messages.

Since said messages become especially important in the new rddmin operating mode, I would propose the following:

- Cap the length of the "remaining deltas" printout to a reasonable length (say, 100 symbols), adding a "... and N more ..." indicator at the end of the list if this limit is reached.
- Allow the user to gain back access to the list of deltas when needed by either 1/allowing the length cap to be tuned via CLI options or 2/logging this information to a file, perhaps in dd.sym.

**Comment by lathuili** [comment]
The no-empty env variable VERROU_DD_QUIET reduces the output (not yet stabilized branch struct_rddmin)

**Comment by HadrienG2** [comment]
Another thing which helped here is the recent idea of only displaying symbols that feature FP instructions. In debug builds, I went from ~10k symbols to ~200, which is much more tractable.
