### ISSUE TITLE
GDB's "stop-at" commands do not work

### ISSUE THREAD

**Issue by HadrienG2** [edf-hpc/verrou#24]
I recently ended up in a case where [valgrind's GDB integration](https://edf-hpc.github.io/verrou/manual-core-adv.html#manual-core-adv.gdbserver) would be useful. Unfortunately, its facilities for controlled execution do not seem to work properly when using Verrou. Here is a non-exhaustive list of things that do not work:

- Setting breakpoints does not seem to have any effect (the program does not stop there)
- When interrupting via Ctrl+C, backtraces are often strange (corrupted?):

```
(gdb) bt 
#0  0x000000000055cf9b in Acts::CuboidVolumeBuilder::buildLayer (this=0x426a880, cfg=...) at /home/hadrien/Bureau/Programmation/acts-core/Core/include/Acts/Tools/CuboidVolumeBuilder.hpp:212
#1  0x000000000055e16a in Acts::CuboidVolumeBuilder::buildVolume (this=0x426a880, cfg=...) at /home/hadrien/Bureau/Programmation/acts-core/Core/include/Acts/Tools/CuboidVolumeBuilder.hpp:278
#2  0x000000000055ee9b in Acts::CuboidVolumeBuilder::trackingVolume (this=0x426a880) at /home/hadrien/Bureau/Programmation/acts-core/Core/include/Acts/Tools/CuboidVolumeBuilder.hpp:321
#3  0x0000000005d0381c in ?? ()
#4  0x0000001ffefe9500 in ?? ()
#5  0x0000001ffefe97b8 in ?? ()
#6  0x0000001ffefe9508 in ?? ()
#7  0x000000000424c0c0 in ?? ()
#8  0x0000000000000000 in ?? ()
```

- "next"/"step"/"finish" seem broken, sometimes they go to an even weirder place where the backtrace is all `??`, other times they just run the program to completion.

It should be noted that only execution control is broken. So when I'm really desperate for a debugger, I can manually sprinkle `asm("int3");` in the code, rebuild, and remove them when I'm done. When setting breakpoints manually using that trick, backtraces and facilities for evaluating expressions, setting memory cells, etc seem to work as intended. But that's obviously not an enjoyable way to use a debugger :wink: 

The same functionalities work just fine when performing the exact same steps, but using memcheck instead of verrou, which is why I think verrou is the culprit.

**Comment by lathuili** [comment]
Hadrien can you test the last version of master to check the bug correction for Acts?
