### ISSUE TITLE
fmaintrin.h

### ISSUE THREAD

**Issue by aminiussi** [edf-hpc/verrou#25]
Hi,
When configuring with fm, the configuration fails with:
>configure:15976: error: A compiler with fmaintrin.h is required for --enable-verrou-fma

Despite the fact that the header is there.

But looking closer, I've found that the actual failure is in the detection test:
```
configure:15941: checking for fmaintrin.h
configure:15959: icpc -c -fma -I/trinity/shared/OCA/softs/gnurt-8.3/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/ -mfma  conftest.cpp >&5
In file included from conftest.cpp(101):
/trinity/shared/OCA/softs/gnurt-8.3/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/fmaintrin.h(25): error: #error directive: "Never use <fmaintrin.h> directly; include <immintrin.h> instead."
  # error "Never use <fmaintrin.h> directly; include <immintrin.h> instead."
    ^

conftest.cpp(107): error: identifier "EXIT_SUCCESS" is undefined
        return EXIT_SUCCESS;
               ^
```

I have the same problem with the platform distribution of gcc:

```
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/fmaintrin.h(25): error: #error directive: "Never use <fmaintrin.h> directly; include <immintrin.h> instead."
  # error "Never use <fmaintrin.h> directly; include <immintrin.h> instead."
    ^
``` 
Regards

**Comment by aminiussi** [comment]
Also, I thing stdlib.h is required in order to use EXIT_SUCESS

**Comment by lathuili** [comment]
I've not redhat vm (at least not yet) to reproduce the problem. Neverthless I hope the changes made in the branch  test_fmaintrin (commit 1457267 ) will solve the detection problem. Can you test?

**Comment by aminiussi** [comment]
Yes, it did build with gnu compiler.
Thanks!

**Comment by aminiussi** [comment]
I did the test on branch test_fmaintrin, checking on master

**Comment by aminiussi** [comment]
So, it build on master to.
