### ISSUE TITLE
Loading VERROU_* env variable with branch 3.16 of valgrind fails

### ISSUE THREAD

**Issue by lathuili** [edf-hpc/verrou#31]
I get the following message :
 Cannot change --rounding-mode=random option dynamically

With the master branch I get the same issue.

**Comment by ffevotte** [comment]
I can reproduce this. It looks like the CLO processing API changed with Valgrind-3.16.

I think I found a way to adapt; I'll try and make a PR fixing this tonight .

**Comment by ffevotte** [comment]
OK, this particular point regarding Valgrind 3.16.1 should now be taken care of. But if we're aiming for full compatibility with 3.16, we're not quite there yet. I openend PR #32 to track the progress made in this direction, and list the remaining steps.
